const API=(window.APP_CONFIG?.API_BASE_URL||"http://localhost:8000").replace(/\/$/,"");
const state={records:[],conversationId:null};
const $=s=>document.querySelector(s); const $$=s=>document.querySelectorAll(s);
function toast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2600)}
async function request(path,options={}){const response=await fetch(API+path,{headers:{"Content-Type":"application/json",...options.headers},...options});if(!response.ok){let detail;try{detail=(await response.json()).detail}catch{}throw new Error(detail||`요청 실패 (${response.status})`)}return response.status===204?null:response.json()}
async function refresh(){try{const [records,summary]=await Promise.all([request("/api/data"),request("/api/data/summary")]);state.records=records;renderSummary(summary);renderRecords();drawChart(records)}catch(e){toast(e.message)}}
function renderSummary(s){const cards=$$(".metric b");cards[0].textContent=s.metrics.sleep_hours?.average??"—";cards[1].textContent=s.metrics.exercise_minutes?.average??"—";cards[2].textContent=s.metrics.healthy_day_rate!=null?`${s.metrics.healthy_day_rate}%`:"—"}
function renderRecords(){const rows=[...state.records].reverse().map(r=>`<tr><td>${r.date}</td><td>${r.value.sleep_hours}h</td><td>${r.value.exercise_minutes}m</td><td>${escapeHtml(r.memo||"—")}</td><td><button onclick="editRecord('${r.id}')">수정</button> <button onclick="deleteRecord('${r.id}')">삭제</button></td></tr>`).join("");$("#recordRows").innerHTML=rows||'<tr><td colspan="5">아직 기록이 없습니다.</td></tr>';$("#recordCount").textContent=`${state.records.length}건`}
function escapeHtml(text){const div=document.createElement("div");div.textContent=text;return div.innerHTML}
window.editRecord=id=>{const r=state.records.find(x=>x.id===id);$("#recordId").value=id;$("#date").value=r.date;$("#sleep").value=r.value.sleep_hours;$("#exercise").value=r.value.exercise_minutes;$("#memo").value=r.memo||"";$("#formTitle").textContent="기록 수정";$("#cancelEdit").classList.remove("hidden");showTab("records")};
window.deleteRecord=async id=>{if(!confirm("이 기록을 삭제할까요?"))return;try{await request(`/api/data/${id}`,{method:"DELETE"});toast("기록을 삭제했습니다.");refresh()}catch(e){toast(e.message)}};
function resetForm(){$("#recordForm").reset();$("#recordId").value="";$("#formTitle").textContent="새 기록";$("#cancelEdit").classList.add("hidden");$("#date").value=new Date().toISOString().slice(0,10)}
$("#recordForm").addEventListener("submit",async e=>{e.preventDefault();const id=$("#recordId").value;const body={date:$("#date").value,value:{sleep_hours:Number($("#sleep").value),exercise_minutes:Number($("#exercise").value)},memo:$("#memo").value};try{await request(`/api/data${id?`/${id}`:""}`,{method:id?"PUT":"POST",body:JSON.stringify(body)});toast(id?"기록을 수정했습니다.":"기록을 추가했습니다.");resetForm();refresh()}catch(err){toast(err.message)}});$("#cancelEdit").onclick=resetForm;
function addMessage(role,content,loading=false){const el=document.createElement("div");el.className=`message ${role}`;el.innerHTML=role==="assistant"?'<span class="avatar">B</span>':"";const p=document.createElement("p");p.textContent=content;el.appendChild(p);if(loading)el.id="loadingMessage";$("#messages").appendChild(el);$("#messages").scrollTop=$("#messages").scrollHeight}
$("#chatForm").addEventListener("submit",async e=>{e.preventDefault();const input=$("#chatInput"),message=input.value.trim();if(!message)return;input.value="";addMessage("user",message);addMessage("assistant","기록을 분석하고 있어요…",true);try{const result=await request("/api/chat",{method:"POST",body:JSON.stringify({message,conversation_id:state.conversationId})});$("#loadingMessage")?.remove();addMessage("assistant",result.answer);state.conversationId=result.conversation_id;loadConversations()}catch(err){$("#loadingMessage")?.remove();toast(err.message)}});$$('.suggestions button').forEach(b=>b.onclick=()=>{$("#chatInput").value=b.textContent;$("#chatForm").requestSubmit()});
$("#newChatBtn").onclick=()=>{state.conversationId=null;$("#conversationStatus").classList.add("hidden");$("#conversationTitle").textContent="";$("#messages").innerHTML='<div class="message assistant"><span class="avatar">B</span><p>새 상담을 시작할게요. 무엇이 궁금한가요?</p></div>'};
async function loadConversations(){try{const list=await request("/api/conversations");$("#conversationList").innerHTML=list.map(c=>`<article class="panel conversation" onclick="openConversation('${c.id}')"><h2>${escapeHtml(c.title)}</h2><p>${escapeHtml(c.messages?.at(-1)?.content||"")}</p><footer><span>${new Date(c.updated_at).toLocaleString("ko-KR")}</span><button class="delete" onclick="event.stopPropagation();removeConversation('${c.id}')">삭제</button></footer></article>`).join("")||'<div class="panel">저장된 대화가 없습니다.</div>'}catch(e){toast(e.message)}}
window.openConversation=async id=>{try{const c=await request(`/api/conversations/${id}`);state.conversationId=id;$("#conversationTitle").textContent=c.title;$("#conversationStatus").classList.remove("hidden");$("#messages").innerHTML="";c.messages.forEach(m=>addMessage(m.role,m.content));showTab("dashboard");toast("저장된 대화를 불러왔습니다.")}catch(e){toast(e.message)}};window.removeConversation=async id=>{if(!confirm("대화를 삭제할까요?"))return;await request(`/api/conversations/${id}`,{method:"DELETE"});if(state.conversationId===id){state.conversationId=null;$("#conversationStatus").classList.add("hidden")}loadConversations()};
function drawChart(records){const canvas=$("#healthChart"),empty=$("#chartEmpty");if(!records.length){canvas.style.display="none";empty.style.display="block";return}canvas.style.display="block";empty.style.display="none";const ctx=canvas.getContext("2d"),dpr=devicePixelRatio||1,w=canvas.clientWidth,h=290;canvas.width=w*dpr;canvas.height=h*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);const data=records.slice(-60),pad=28,x=i=>pad+i*(w-pad*2)/Math.max(1,data.length-1),ySleep=v=>h-pad-(v/12)*(h-pad*2),yEx=v=>h-pad-(v/120)*(h-pad*2);ctx.strokeStyle=getComputedStyle(document.body).getPropertyValue('--line');ctx.lineWidth=1;for(let i=0;i<5;i++){const y=pad+i*(h-pad*2)/4;ctx.beginPath();ctx.moveTo(pad,y);ctx.lineTo(w-pad,y);ctx.stroke()}function line(getY,color){ctx.strokeStyle=color;ctx.lineWidth=2.5;ctx.beginPath();data.forEach((r,i)=>{const y=getY(r);i?ctx.lineTo(x(i),y):ctx.moveTo(x(i),y)});ctx.stroke()}line(r=>ySleep(r.value.sleep_hours),"#527766");line(r=>yEx(r.value.exercise_minutes),"#c6dc73")}
function showTab(id){$$('.tab-panel').forEach(p=>p.classList.toggle('active',p.id===id));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.tab===id));if(id==='history')loadConversations();if(id==='dashboard')requestAnimationFrame(()=>drawChart(state.records))}$$('.nav').forEach(n=>n.onclick=()=>showTab(n.dataset.tab));
$("#seedBtn").onclick=async()=>{try{const r=await request("/api/data/seed",{method:"POST"});toast(r.message);refresh()}catch(e){toast(e.message)}};$("#exportBtn").onclick=()=>window.open(`${API}/api/data/export.csv`,"_blank");$("#themeBtn").onclick=()=>{document.body.classList.toggle("dark");localStorage.setItem("theme",document.body.classList.contains("dark")?"dark":"light");drawChart(state.records)};if(localStorage.getItem("theme")==="dark")document.body.classList.add("dark");window.addEventListener("resize",()=>drawChart(state.records));resetForm();refresh();
